### ISSUE TITLE
Do underlying shadow elements support class names and inline styles?

### ISSUE THREAD

**Issue by teddyfullstack** [microsoft/vscode-webview-ui-toolkit#550]
### Feature request

I want to justify my button content to the left, but the added class `justify-left` is put on the `<vscode-button>` element, which has no effect. I wonder how I can add the class to the underlying `<button>` element in the shadow root.

### Expected behavior

Allow passing class names or inline styles to style the shadow elements.

### Current behavior

Cannot style the button because the class names and inline styles are applied to the wrapper elements.

### Use case

I'm trying to justify my button content to the left.

### Screenshots/references

It would work if the class is passed to the actual `<button>` element instead:

<img width="955" alt="Screenshot 2024-04-16 at 18 08 14" src="https://github.com/microsoft/vscode-webview-ui-toolkit/assets/29925961/27c4193e-9a48-46de-b271-757a938271a0">

**Comment by dinghar** [comment]
+1 I'm trying to disable the default blue outline of a textarea but am unable to accomplish this

**Comment by hawkticehurst** [comment]
Hey @teddyfullstack! It's not well documented (apologies) but the `part` attribute/psuedo-element selector can be used to access/style elements within the shadow root.

You can read more about [`::part()` on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/::part), but here's a basic example to give you an idea:

```css
vscode-button::part(control) {
  background-color: red;
  /* insert other arbitrary styles */
}
vscode-button::part(control):hover {
  background-color: blue;
  /* insert other arbitrary styles */
}
```

Extra notes:

- The part name "control" comes from FAST Foundation and is used widely across other components in the toolkit
- There's no easy way to apply a class name to the elements in the shadow root thanks to how shadow DOM works and how FAST is built
